name = "leanHelpers"
version = "0.1.0"
defaultTargets = ["lean-helpers", "import-graph"]

[[lean_lib]]
name = "LeanHelpers"

[[lean_exe]]
name = "lean-helpers"
root = "Main"

[[lean_exe]]
name = "import-graph"
root = "LeanHelpers.ImportGraph"
