name = "leanHelpers"
version = "0.1.0"
defaultTargets = ["lean-helpers", "import-graph", "gen-all"]

[[lean_lib]]
name = "LeanHelpers"

[[lean_exe]]
name = "lean-helpers"
root = "Main"

[[lean_exe]]
name = "import-graph"
root = "LeanHelpers.ImportGraph"

[[lean_exe]]
name = "gen-all"
root = "LeanHelpers.GenAll"
