name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1