name: Release

on:
  release:
    types: [created]
  workflow_dispatch: {}

permissions:
  contents: write  # Needed to upload release assets

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. Build
      - name: Build
        uses: leanprover/lean-action@v1
        with:
          lake-package-directory: "src"

      # 3. Zip the build result
      - name: Zip build result
        run: |
          zip -r "build-${{ matrix.os }}.zip" src/.lake/build

      # 4. Upload as release artifact
      - name: Upload release artifact
        uses: softprops/action-gh-release@v2
        with:
          files: "build-${{ matrix.os }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
