name: Release

on:
  release:
    types: [created]
  workflow_dispatch: {}

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. Install Nix with flake support
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      # 3. Build your flake
      - name: Build flake
        run: |
          nix build
          # Replace myPackage with the attribute in your flake

      # 4. Upload as release artifact
      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: result
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
